# Generated by Django 5.2.2 on 2025-07-16 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dice',
            options={'verbose_name_plural': 'Dice'},
        ),
    ]
