# Generated by Django 5.2.2 on 2025-06-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='product_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_charge',
            field=models.BooleanField(default=False),
        ),
    ]
