# Generated by Django 5.2.2 on 2025-06-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_date_product_day_product_game_master_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='game_dates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_campaign',
            field=models.BooleanField(default=False),
        ),
    ]
